# Generated by Django 4.2.1 on 2023-05-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0002_rename_doc_reciever_document_doc_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Doc_Content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='Doc_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
